---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    security.opendatahub.io/enable-auth: 'false'
    openshift.io/description: ''
    openshift.io/display-name: {{ .Values.name }}
    serving.kserve.io/deploymentMode: RawDeployment
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/hardware-profile-name: default-profile
    opendatahub.io/model-type: predictive
    {{- if eq .Values.version "latest" }}
    opendatahub.io/connections: quay-conn
    {{- end }}
    {{- if and .Values.autoscaling (not .Values.keda) }}
    serving.kserve.io/autoscalerClass: hpa
    {{- end }}
    {{- if .Values.keda }}
    serving.kserve.io/autoscalerClass: keda
    {{- end }}
    opendatahub.io/model-type: predictive
  name: {{ .Values.name }}
  finalizers:
    - inferenceservice.finalizers
    - odh.inferenceservice.finalizers
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    {{- if and .Values.autoscaling (not .Values.keda) }}
    scaleTarget: 5
    scaleMetric: memory
    {{- end }}
    automountServiceAccountToken: false
    deploymentStrategy:
      type: RollingUpdate
    {{- if eq .Values.version "latest" }}
    imagePullSecrets:
      - name: quay-conn
    {{- end }}
    {{ if and .Values.autoscaling (not .Values.keda) }}
    maxReplicas: 2
    {{- else if .Values.keda }}
    maxReplicas: 5
    {{- else }}
    maxReplicas: 1
    {{- end }}
    minReplicas: 1
    {{- if .Values.keda }}
    autoScaling:
      metrics:
        - external:
            authenticationRef:
              authModes: bearer
              authenticationRef:
                name: inference-prometheus-auth
            metric:
              backend: prometheus
              query: 'ovms_current_requests{namespace="{{ .Release.Namespace }}", name="jukebox", version="1"}'
              serverAddress: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
            target:
              type: Value
              value: '1'
          type: External
    {{- end}}
    containers:
      - args:
          - '--model_name={{ .Values.name }}'
          - '--port=8001'
          - '--rest_port=8085'
          - '--model_path=/mnt/models'
          - '--file_system_poll_wait_seconds=0'
          - '--grpc_bind_address=0.0.0.0'
          - '--rest_bind_address=0.0.0.0'
          - '--target_device=AUTO'
          - '--metrics_enable'
        env:
          - name: TS_SERVICE_ENVELOPE
            value: kserve
          - name: STORAGE_URI
            value: oci://{{ .Values.image_repository | default "quay.io" }}/{{ .Values.image_namespace }}/{{ .Values.name }}:{{ .Values.version }}
        image: 'registry.redhat.io/rhoai/odh-openvino-model-server-rhel9@sha256:defd01ac5a37a6138de73a8f1b10c676a2efa617238049378f8bc63fb0eb00c6'
        name: kserve-container
        resources:
          limits:
            cpu: '3'
            memory: 8Gi
          requests:
            cpu: '1'
            memory: 4Gi
      - args:
          - '--model_name={{ .Values.name }}'
          - '--predictor_protocol=v2'
          - '--http_port=8080'
          - '--grpc_port=8081'
          - '--predictor_host=localhost:8085'
          - '--predictor_use_ssl=False'
          - '--scaler_file_path=/mnt/models/1/artifacts/scaler.pkl'
          - '--encoder_file_path=/mnt/models/1/artifacts/label_encoder.pkl'
        command:
          - python
          - '-m'
          - music_transformer
        image: 'quay.io/rhoai-mlops/music_transformer:0.3'
        name: transformer-container
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi