{{ if eq .Values.image_signing true }}
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-signing
spec:
  workspaces:
    - name: output
  params:
    - name: APPLICATION_NAME
      description: Name of the application
      type: string
    - name: PROJECT_NAME
      description: Name of the team that doing this exercise :)
      type: string
    - name: VERSION
      description: Version of the application
      type: string
    - name: COSIGN_VERSION
      type: string
      description: Version of cosign CLI
      default: 2.4.3
    - name: WORK_DIRECTORY
      description: Directory to start build in (handle multiple branches)
      type: string
  steps:
    - name: image-signing
      image: quay.io/openshift/origin-cli:4.12
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      script: |
        #!/usr/bin/env bash
        curl -skL -o /tmp/cosign https://github.com/sigstore/cosign/releases/download/v$(params.COSIGN_VERSION)/cosign-linux-amd64
        chmod -R 775 /tmp/cosign

        oc registry login
        /tmp/cosign sign --key k8s://$(params.PROJECT_NAME)-toolings/$(params.PROJECT_NAME)-cosign `oc registry info`/$(params.PROJECT_NAME)-test/$(params.APPLICATION_NAME):$(params.VERSION) --allow-insecure-registry
{{- end }}