{{ if eq .Values.model_scanning true }}
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: scan-model
spec:
  workspaces:
    - name: output
  params:
    - name: APPLICATION_NAME
      description: Name of the application
      type: string
  steps:
  - name: scan-model
    workingDir: $(workspaces.output.path)
    image: registry.redhat.io/ubi9/python-311@sha256:fc669a67a0ef9016c3376b2851050580b3519affd5ec645d629fd52d2a8b8e4a
    command: ["/bin/sh", "-c"]
    args:
    - |
      python3 -m pip install modelscan[tensorflow] numpy==1.26.4
      modelscan -p $(params.APPLICATION_NAME).keras --show-skipped
{{- end }}