---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    security.opendatahub.io/enable-auth: 'false'
    openshift.io/description: ''
    openshift.io/display-name: {{ .Values.name }}
    serving.kserve.io/deploymentMode: RawDeployment
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/hardware-profile-name: default-profile
    opendatahub.io/connections: quay-conn
    opendatahub.io/model-type: predictive
  name: {{ .Values.name }}
  finalizers:
    - inferenceservice.finalizers
    - odh.inferenceservice.finalizers
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: RollingUpdate
    imagePullSecrets:
      - name: quay-conn
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: onnx
        version: '1'
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 4Gi
        requests:
          cpu: '2'
          memory: 4Gi
      runtime: {{ .Values.name }}
      storageUri: oci://{{ .Values.image_repository | default "quay.io" }}/{{ .Values.image_namespace }}/{{ .Values.name }}:{{ .Values.version }}
